version: "3.5"

services:
  one_day_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - one-day-proxy
    environment:
      - PMA_HOST=one_day_mysql
      - UPLOAD_LIMIT= 2000M
    ports:
      - "8000:80"
    volumes:
      - ./config/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
    container_name: one_day_phpmyadmin
  one_day_mysql:
    image: mysql:5.6
    networks:
      - one-day-proxy
    environment:
      - TZ=Asia/Taipei
      - MYSQL_ROOT_PASSWORD=root@root@root
    volumes:
      - ./init_data:/docker-entrypoint-initdb.d
      - ./db/mysql/mysql_data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    container_name: one_day_mysql

networks:
  one-day-proxy:
    external:
      name: one-day-network
